### ISSUE TITLE
Installation of Par4all Error

### ISSUE THREAD

**Issue by Premas** [Par4All/par4all#1]
We are getting this error while installing par4all

fortran/cpp.o:/home/prema/Documents/par4all-p4a/build/pips/src/Passes/fortran95/build/4.4.5/gcc/../../../gcc-4.4.5/gcc/toplev.h:197: first defined here
libbackend.a(sched-deps.o): In function `floor_log2':
/home/prema/Documents/par4all-p4a/build/pips/src/Passes/fortran95/build/4.4.5/gcc/../../../gcc-4.4.5/gcc/toplev.h:191: multiple definition of `floor_log2'
fortran/cpp.o:/home/prema/Documents/par4all-p4a/build/pips/src/Passes/fortran95/build/4.4.5/gcc/../../../gcc-4.4.5/gcc/toplev.h:191: first defined here
libbackend.a(sched-deps.o): In function `exact_log2':
/home/prema/Documents/par4all-p4a/build/pips/src/Passes/fortran95/build/4.4.5/gcc/../../../gcc-4.4.5/gcc/toplev.h:197: multiple definition of `exact_log2'
fortran/cpp.o:/home/prema/Documents/par4all-p4a/build/pips/src/Passes/fortran95/build/4.4.5/gcc/../../../gcc-4.4.5/gcc/toplev.h:197: first defined here
libbackend.a(sched-ebb.o): In function `floor_log2':
/home/prema/Documents/par4all-p4a/build/pips/src/Passes/fortran95/build/4.4.5/gcc/../../../gcc-4.4.5/gcc/toplev.h:191: multiple definition of `floor_log2'
fortran/cpp.o:/home/prema/Documents/par4all-p4a/build/pips/src/Passes/fortran95/build/4.4.5/gcc/../../../gcc-4.4.5/gcc/toplev.h:191: first defined here
libbackend.a(sched-ebb.o): In function `exact_log2':
/home/prema/Documents/par4all-p4a/build/pips/src/Passes/fortran95/build/4.4.5/gcc/../../../gcc-4.4.5/gcc/toplev.h:197: multiple definition of `exact_log2'
fortran/cpp.o:/home/prema/Documents/par4all-p4a/build/pips/src/Passes/fortran95/build/4.4.5/gcc/../../../gcc-4.4.5/gcc/toplev.h:197: first defined here
libbackend.a(ddg.o): In function `floor_log2':
/home/prema/Documents/par4all-p4a/build/pips/src/Passes/fortran95/build/4.4.5/gcc/../../../gcc-4.4.5/gcc/toplev.h:191: multiple definition of `floor_log2'
fortran/cpp.o:/home/prema/Documents/par4all-p4a/build/pips/src/Passes/fortran95/build/4.4.5/gcc/../../../gcc-4.4.5/gcc/toplev.h:191: first defined here
libbackend.a(ddg.o): In function `exact_log2':
/home/prema/Documents/par4all-p4a/build/pips/src/Passes/fortran95/build/4.4.5/gcc/../../../gcc-4.4.5/gcc/toplev.h:197: multiple definition of `exact_log2'
fortran/cpp.o:/home/prema/Documents/par4all-p4a/build/pips/src/Passes/fortran95/build/4.4.5/gcc/../../../gcc-4.4.5/gcc/toplev.h:197: first defined herecollect2: ld returned 1 exit status
make[5]: *** [f951] Error 1
make[4]: *** [build-stage2] Error 2
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
p4a_setup: Command 'make' in /home/prema/Documents/par4all-p4a/build/pips failed with exit code 2

**Comment by keryell** [comment]
That is curious.
But all this is so old and this Fortran95 had never worked in par4all, only Fortran77.
So just skipping the compilation would be fine.

You have to find a way to remove `--enable-fortran95` from the setup.

Oh, actually it looks like some people have solved the issue in an alternative way on http://www.fractalforums.com/programming/omp-vs-par4all

They could make a pull request... :)

**Comment by Premas** [comment]
Thank you. It worked :+1:  . I am working with C parallelization, so currently I have removed --enable-fortran95 from the setup file. Now Par4all is installed successfully.
