### ISSUE TITLE
Par4all Parallelization Error 

### ISSUE THREAD

**Issue by Premas** [Par4All/par4all#2]
When I try to use OpenMP parallelization for parallelizing the doitgen benchmark of Polybench suite, I get the following error.  I have installed Par4all-1.4.6 X86_64 bit version.

p4a: PIPS: user warning in generic_proper_effects_of_complex_address_call_expression: PIPS currently does not know how to precisely handle address values used in complex call expressions expression
p4a: PIPS: user warning in set_debug_stack_pointer: debug level stack is set to 1
p4a: PIPS: user warning in safe_concurrent_apply: Request aborted under pipsmake: capply COARSE_GRAIN_PARALLELIZATION for module [doitgen!init_array,doitgen!print_array,kernel_doitgen,main,polybench!rtclock,polybench!xmalloc,polybench_alloc_data,polybench_flush_cache,polybench_free_data,polybench_prepare_instruments,polybench_timer_print,polybench_timer_start,polybench_timer_stop].
p4a: Not removing database directory /home/prema/polybench-c-4.2/P4AguMw.database
p4a: Unhandled RuntimeError: capply phase COARSE_GRAIN_PARALLELIZATION failed without setting error message
p4a: Traceback (most recent call last):
  File "/home/prema/Tools/build_par4all/lib/python2.6/site-packages/pips/p4a_opts.py", line 324, in exec_and_deal_with_errors
    fun()
  File "/home/prema/Tools/build_par4all/bin/p4a", line 701, in main
    raise output.exception
RuntimeError: capply phase COARSE_GRAIN_PARALLELIZATION failed without setting error message
p4a: To get a more verbose output, pass -v
p4a: Alternatively, you can pass --log to log -vv output to a file
p4a: You may report this error to the Par4All team by running again using --report <your email address>
p4a: Pass --report-files to attach input/processed files to the report email (CAREFUL: this assumes you are allowed and willing to send us potentially confidential files!)

Could you please help me in solving this issue?

**Comment by keryell** [comment]
Can you attach the code causing the error?
Also you could ask for a more verbose output as suggested.

**Comment by Premas** [comment]
I have attached the error file and the complete code. Please check it.

[p4a_error.txt](https://github.com/Par4All/par4all/files/1070296/p4a_error.txt)
[doitgen.tar.gz](https://github.com/Par4All/par4all/files/1070297/doitgen.tar.gz)

**Comment by bac-4all** [comment]
Hi,
      
      It seems to be due to an error in the linear library during
      precondition computations. It may be due to an overflow error.
      Could you try to run it with the doitgen MINI_DATASET macro
      defined, to check whether the error still occurs?
      
      Regards,
      
      Béatrice.
    
    Le 13/06/2017 à 06:24, Premas a écrit :
    
    
      I have attached the error file and the complete code. Please
        check it.
      p4a_error.txt
        doitgen.tar.gz
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Par4All/par4all","title":"Par4All/par4all","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Par4All/par4all"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Premas in #2: I have attached the error file and the complete code. Please check it.\r\n\r\n\r\n[p4a_error.txt](https://github.com/Par4All/par4all/files/1070296/p4a_error.txt)\r\n[doitgen.tar.gz](https://github.com/Par4All/par4all/files/1070297/doitgen.tar.gz)\r\n\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Par4All/par4all/issues/2#issuecomment-308003051"}}}

**Comment by keryell** [comment]
Thanks Béatrice for the support. :-)

By looking at `print_array`, I wonder whether if this is not where the overflow happen in the test with array linearization + modulo code.

You might first just remove the full line to test if it avoids the crash, but Par4All will probably remove all the code since it will be dead code. :-)

Then you could try to replace  `polybench_prevent_dce(print_array(nr, nq, np,  POLYBENCH_ARRAY(A)));` by just a printf of the first element of A.

**Comment by Premas** [comment]
Thank you. After removing the line **polybench_prevent_dce(print_array(nr, nq, np, POLYBENCH_ARRAY(A)));**, the code is now parallelized. I included the line after getting the parallelized result.
